version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: server_nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - private-net

  mysql:
    container_name: my_mysql
    env_file:
      - ./.mysql/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - private-net

networks:
  private-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.98.0/24
          gateway: 172.20.98.1
    internal: true
